//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMute.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carpool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carpool()
        {
            this.User_Carpool = new HashSet<User_Carpool>();
        }
    
        public int Carpool_ID { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string Leader { get; set; }
        public string DaysAvailable { get; set; }
        public int AvailbaleSeats { get; set; }
        public System.TimeSpan DepartureTime { get; set; }
        public System.TimeSpan ArrivalTime { get; set; }
        public string Notes { get; set; }
        public Nullable<int> NumberOfUsers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Carpool> User_Carpool { get; set; }
    }
}
