//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMute.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Carpool
    {
        public int User_ID { get; set; }
        public int Carpool_ID { get; set; }
        public Nullable<int> NumberOfUsers { get; set; }
    
        public virtual Carpool Carpool { get; set; }
        public virtual User User { get; set; }
    }
}
